# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ed3eb8925d0b5b06f8f1ad065c322e442e6349397ae75a7a6427dccb0d78cadc1552dd25d1ce289deaeb67c6d1229351f1afbc100d8ecc1b712a66af64c9fa3

test:
  secret_key_base: 224ef0f788899c45c2d5ac3eced891f4b79029a5ee30068bee8153154a4c3f58ed1b3e59799465badc4392cddb0a372c6a181c0f1c4f4b4bd8476d310a085ba1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
